#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Dec 20, 2020 02:38:17 AM PKT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m55" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 930x661+-1167+77
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 930 661
    wm minsize $top 930 661
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab47 \
        -font TkDefaultFont -foreground black -text {Project Setup} \
        -background $vTcl(actual_gui_bg) -height 645 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 916 
    vTcl:DefineAlias "$top.lab47" "setupwindow" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab47
    labelframe $site_3_0.lab48 \
        -font TkDefaultFont -foreground black -text {Folder Location} \
        -background $vTcl(actual_gui_bg) -height 99 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 895 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab48
    entry $site_4_0.ent47 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 734 
    vTcl:DefineAlias "$site_4_0.ent47" "folderlocation_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command openfolder -cursor hand2 \
        -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$site_4_0.but48" "browse_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent47 \
        -in $site_4_0 -x 0 -relx 0.01 -y 0 -rely 0.323 -width 734 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.848 -y 0 -rely 0.309 -width 127 \
        -relwidth 0 -height 39 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab50 \
        -font TkDefaultFont -foreground black -text {Target URL} \
        -background $vTcl(actual_gui_bg) -height 109 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 897 
    vTcl:DefineAlias "$site_3_0.lab50" "Labelframe2_2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab50
    entry $site_4_0.ent50 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 874 
    vTcl:DefineAlias "$site_4_0.ent50" "targeturl_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent50 \
        -in $site_4_0 -x 0 -relx 0.011 -y 0 -rely 0.336 -width 874 \
        -relwidth 0 -height 40 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab51 \
        -font TkDefaultFont -foreground black -text {Project Name} \
        -background $vTcl(actual_gui_bg) -height 94 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 892 
    vTcl:DefineAlias "$site_3_0.lab51" "Labelframe3_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab51
    entry $site_4_0.ent52 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 864 
    vTcl:DefineAlias "$site_4_0.ent52" "projectname_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.ent52 \
        -in $site_4_0 -x 0 -relx 0.011 -y 0 -rely 0.319 -width 874 \
        -relwidth 0 -height 40 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command startcrawl -cursor hand2 \
        -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #000000 \
        -pady 0 -text {Start Crawling} 
    vTcl:DefineAlias "$site_3_0.but54" "startcrawl" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 19 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #df151b -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #646464646464 -text {** Sorry, This path is invalid.} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.046 -width 0 \
        -relwidth 0.979 -height 0 -relheight 0.153 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.214 -width 0 \
        -relwidth 0.981 -height 0 -relheight 0.166 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.397 -width 0 \
        -relwidth 0.981 -height 0 -relheight 0.166 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.36 -y 0 -rely 0.775 -width 247 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.131 -y 0 -rely 0.636 -width 0 \
        -relwidth 0.737 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    menu $top.m55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab45 \
        -font TkDefaultFont -foreground black -text {Crawling ... } \
        -background $vTcl(actual_gui_bg) -height 680 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 1087 
    vTcl:DefineAlias "$top.lab45" "crawlwindow" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab45
    labelframe $site_3_0.lab47 \
        -font TkDefaultFont -foreground black -text Status \
        -background $vTcl(actual_gui_bg) -height 76 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 897 
    vTcl:DefineAlias "$site_3_0.lab47" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab47
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 22 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text {Generating sitemap ...} 
    vTcl:DefineAlias "$site_4_0.lab48" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #006fe8 -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f4f2f2 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Start 
    vTcl:DefineAlias "$site_4_0.but51" "startbtn" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #df092e -disabledforeground #a3a3a3 \
        -font {-family {Microsoft PhagsPa} -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f4f2f2 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Break 
    vTcl:DefineAlias "$site_4_0.but52" "breakop" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab48 \
        -in $site_4_0 -x 0 -relx 0.045 -y 0 -rely 0.132 -width 0 \
        -relwidth 0.598 -height 0 -relheight 0.803 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.668 -y 0 -rely 0.263 -width 127 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but52 \
        -in $site_4_0 -x 0 -relx 0.835 -y 0 -rely 0.257 -width 127 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab49 \
        -font TkDefaultFont -foreground black -text {LOG data} \
        -background $vTcl(actual_gui_bg) -height 525 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 899 
    vTcl:DefineAlias "$site_3_0.lab49" "log" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab49
    text $site_4_0.tex50 \
        -background #cbc9ca -font {-family {Microsoft PhagsPa} -size 12} \
        -foreground black -height 494 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground #858585 -width 878 -wrap word 
    $site_4_0.tex50 configure -font "-family {Microsoft PhagsPa} -size 12"
    $site_4_0.tex50 insert end text
    vTcl:DefineAlias "$site_4_0.tex50" "textbox" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tex50 \
        -in $site_4_0 -x 0 -relx 0.011 -y 0 -rely 0.037 -width 0 \
        -relwidth 0.977 -height 0 -relheight 0.941 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.009 -y 0 -rely 0.059 -width 0 \
        -relwidth 0.825 -height 0 -relheight 0.112 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.009 -y 0 -rely 0.206 -width 0 \
        -relwidth 0.826 -height 0 -relheight 0.771 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.015 -width 0 -relwidth 0.985 \
        -height 0 -relheight 0.976 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.015 -width 0 -relwidth 1.171 \
        -height 0 -relheight 0.999 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

